MWPW-131170 Refactor scripts.js
adobecom/helpx-internal pull request #18
Opened 2023-05-17 04:30 UTC by sharmrj

https://jira.corp.adobe.com/browse/MWPW-131170

[docx file](https://adobe.sharepoint.com/:w:/r/sites/adobecom/_layouts/15/Doc.aspx?sourcedoc=%7B8D1D7F5A-A46E-4CBA-B84E-9FC68A1B4483%7D&file=new-zealand---gst-.docx&action=default&mobileredirect=true)

original helpx-internal page: https://helpx-internal.corp.adobe.com/content/help/en/internal/individual/policy-process/new-zealand---gst-.html

milo page: https://misc--helpx-internal--adobecom.hlx.page/content/help/en/internal/individual/policy-process/new-zealand-gst

2023-05-19 07:09 UTC, coorghari submitted a review, later dismissed

2023-05-23 05:18 UTC, praveenrv approved these changes, later dismissed

2023-05-23 06:28 UTC, nkthakur48 requested changes

2023-05-23 06:28 UTC, nkthakur48 commented on tools/importer/rules/toc.js
> +  /* const toc = document.querySelector('.toc');
Remove comments

2023-05-23 06:45 UTC, sharmrj commented on tools/importer/rules/toc.js
> +  /* const toc = document.querySelector('.toc');
I've done so

2023-05-24 05:16 UTC, coorghari approved these changes

2023-05-24 17:11 UTC, adeshmukh-1585 approved these changes

2023-05-26 05:15 UTC, nkthakur48 approved these changes

2023-05-26 05:15 UTC, merged