Numerous Bugfixes (see below)
adobecom/helpx-internal pull request #22
Opened 2023-06-01 10:14 UTC by sharmrj

[MWPW-132063](https://jira.corp.adobe.com/browse/MWPW-132063): solved by 340c28704cd0e3f984a35336afc0d418d9ea9859

2023-06-09 09:32 UTC, adeshmukh-1585 approved these changes, later dismissed

2023-06-14 08:14 UTC, SRaj1234 requested changes

2023-06-14 08:14 UTC, SRaj1234 commented on blocks/toc/toc.css
> +  .page-title .toc-mobile-dra
@sharmrj  Can you check if the media query is needed or not? It looks like incomplete code. Please check.

2023-06-14 08:14 UTC, SRaj1234 commented on blocks/toc/toc.js
> +  // event.preventDefault();
@sharmrj If this line is not needed, then better to remove it.

2023-06-14 11:06 UTC, sharmrj commented on blocks/toc/toc.css
> +  .page-title .toc-mobile-dra
good catch. The code was deleted accidentally; I've added it back in.

2023-06-14 11:08 UTC, sharmrj commented on blocks/toc/toc.js
> +  // event.preventDefault();
I've done so

2023-06-28 19:28 UTC, nkthakur48 approved these changes

2023-06-28 19:28 UTC, merged